# Generated by Django 3.0.7 on 2020-06-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200615_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(max_length=255, null=True, upload_to='profile-pictures/'),
        ),
    ]
